# Generated by Django 4.1.7 on 2023-03-26 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communityApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFavorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='replayreports',
            name='replay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayReports', to='communityApp.commentreplays'),
        ),
        migrations.AddField(
            model_name='replayreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayReports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communityApp.usertest'),
        ),
        migrations.AddField(
            model_name='postreports',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReports', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='postreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrates',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRates', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='postrates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRates', to='communityApp.usertest'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes', to='communityApp.usertest'),
        ),
        migrations.AddField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImages', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='commentreports',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReports', to='communityApp.comment'),
        ),
        migrations.AddField(
            model_name='commentreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreplays',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplays', to='communityApp.comment'),
        ),
        migrations.AddField(
            model_name='commentreplays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='communityApp.posts'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postlikes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='Already Liked'),
        ),
    ]
