# Generated by Django 4.1.7 on 2023-03-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='commentreplays',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplays', to='communityApp.comment'),
        ),
        migrations.AlterField(
            model_name='commentreplays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplays', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='commentreports',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReports', to='communityApp.comment'),
        ),
        migrations.AlterField(
            model_name='commentreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReports', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImages', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='postrates',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRates', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='postrates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRates', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='postrates',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Down'), (0, 'Hold'), (1, 'Up')], default=0),
        ),
        migrations.AlterField(
            model_name='postreports',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReports', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='postreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReports', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='replayreports',
            name='replay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayReports', to='communityApp.commentreplays'),
        ),
        migrations.AlterField(
            model_name='replayreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayReports', to='communityApp.usertest'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFavorites', to='communityApp.posts'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFavorites', to='communityApp.usertest'),
        ),
    ]
