# Generated by Django 4.1.6 on 2023-03-30 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communityApp', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postrates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postRates', to=settings.AUTH_USER_MODEL),
        ),
    ]
