# Generated by Django 4.1.7 on 2023-03-20 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0003_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='main_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts/%y/%m/%d'),
        ),
    ]
