# Generated by Django 4.1.7 on 2023-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0006_remove_postlikes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Down'), (0, 'Hold'), (1, 'Up')], default=0),
        ),
    ]
