# Generated by Django 4.1.7 on 2023-03-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0007_postlikes_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlikes',
            name='Already Liked',
        ),
    ]
