# Generated by Django 4.1.7 on 2023-03-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0008_remove_postlikes_already liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='main_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts/%y/%m/%d'),
        ),
        migrations.AddConstraint(
            model_name='postlikes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='Already Liked'),
        ),
    ]
