# Generated by Django 4.1.7 on 2023-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0009_usertest_main_image_postlikes_already liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='main_Image',
        ),
        migrations.AddField(
            model_name='usertest',
            name='main',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/%y/%m/%d'),
        ),
    ]
