# Generated by Django 4.1.7 on 2023-03-26 22:56

import campApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/activeCampsSub/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('start_date', models.DateField(help_text='Enter the Start date of Camp It Must Be greater Than Today', validators=[campApp.models.no_past])),
                ('end_date', models.DateField(help_text='Enter the End date of Camp It Must Be less Than Start Date')),
                ('camp_time', models.TimeField(default=django.utils.timezone.now)),
                ('main_Image', models.ImageField(upload_to='media/activeCampsMain/%y/%m/%d')),
                ('price_per_child', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('max_num_of_enrolment', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_num_of_enrolment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCampVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeesNamesAges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='CampCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='media/qrcods/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedCampVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampVideo', to='campApp.activecamps')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('av_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('started_date', models.DateField(help_text='Enter the Start date of Camp It Must Be greater Less Today', validators=[campApp.models.no_future])),
                ('ended_date', models.DateField(help_text='Enter the End date of Camp It Must Be less Than Start Date')),
                ('main_Image', models.ImageField(upload_to='media/activeCampsMain/%y/%m/%d')),
                ('numOfAttendee', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampCategory', to='campApp.campcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampCategory', to='campApp.camplocation')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedCampImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/finishedCampsSub/%y/%m/%d')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampImages', to='campApp.activecamps')),
            ],
        ),
        migrations.CreateModel(
            name='CampsEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_attendees', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('had_attend', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('enrolment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsEnrollment', to='campApp.activecamps')),
            ],
        ),
    ]
