# Generated by Django 4.1.7 on 2023-03-15 19:41

import campApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecamps',
            name='duration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='end_date',
            field=models.DateTimeField(help_text='Enter the End date of Camp'),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='max_num_of_enrolment',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='offer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='start_date',
            field=models.DateField(help_text='Enter the Start date of Camp', validators=[campApp.models.no_past]),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
