# Generated by Django 4.1.7 on 2023-03-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communityApp', '0001_initial'),
        ('campApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsEnrollment', to='communityApp.usertest'),
        ),
        migrations.AddField(
            model_name='attendeesnamesages',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendeesNamesAges', to='campApp.campsenrollment'),
        ),
        migrations.AddField(
            model_name='activecampvideos',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campVideo', to='campApp.activecamps'),
        ),
        migrations.AddField(
            model_name='activecamps',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campCategory', to='campApp.campcategory'),
        ),
        migrations.AddField(
            model_name='activecamps',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campCategory', to='campApp.camplocation'),
        ),
        migrations.AddField(
            model_name='activecampimages',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campImages', to='campApp.activecamps'),
        ),
        migrations.AlterUniqueTogether(
            name='campsenrollment',
            unique_together={('camp', 'user')},
        ),
    ]
