# Generated by Django 4.1.7 on 2023-03-15 19:52

import campApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0002_alter_activecamps_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecamps',
            name='camp_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='end_date',
            field=models.DateTimeField(help_text='Enter the End date of Camp It Must Be less Than Start Date'),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='start_date',
            field=models.DateField(help_text='Enter the Start date of Camp It Must Be greater Than Today', validators=[campApp.models.no_past]),
        ),
    ]
