# Generated by Django 4.1.7 on 2023-03-15 20:01

import campApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0003_activecamps_camp_time_alter_activecamps_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='start_date',
            field=models.DateTimeField(help_text='Enter the Start date of Camp It Must Be greater Than Today', validators=[campApp.models.no_past]),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campCategory', to='campApp.camplocation'),
        ),
    ]
