# Generated by Django 4.1.7 on 2023-03-15 20:12

import campApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0004_camplocation_alter_activecamps_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecamps',
            name='end_date',
            field=models.DateField(help_text='Enter the End date of Camp It Must Be less Than Start Date'),
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='start_date',
            field=models.DateField(help_text='Enter the Start date of Camp It Must Be greater Than Today', validators=[campApp.models.no_past]),
        ),
    ]
