# Generated by Django 4.1.7 on 2023-03-15 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0003_alter_posts_title'),
        ('campApp', '0005_alter_activecamps_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecamps',
            name='main_Image',
            field=models.ImageField(upload_to='media/activeCampsMain/%y/%m/%d'),
        ),
        migrations.CreateModel(
            name='CampsEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_attendees', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('has_attend', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('enrolment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsEnrollment', to='campApp.activecamps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsEnrollment', to='communityApp.usertest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCampVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campVideo', to='campApp.activecamps')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCampImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/activeCampsSub/%y/%m/%d')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campImages', to='campApp.activecamps')),
            ],
        ),
    ]
