# Generated by Django 4.1.7 on 2023-03-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0006_alter_activecamps_main_image_campsenrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsenrollment',
            name='title',
        ),
        migrations.AlterField(
            model_name='activecamps',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
