# Generated by Django 4.1.7 on 2023-03-19 20:53

import campApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0008_rename_has_attend_campsenrollment_had_attend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedCampVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampVideo', to='campApp.activecamps')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedCamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('started_date', models.DateField(help_text='Enter the Start date of Camp It Must Be greater Than Today', validators=[campApp.models.no_future])),
                ('ended_date', models.DateField(help_text='Enter the End date of Camp It Must Be less Than Start Date')),
                ('main_Image', models.ImageField(upload_to='media/activeCampsMain/%y/%m/%d')),
                ('numOfAttendee', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampCategory', to='campApp.campcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampCategory', to='campApp.camplocation')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedCampImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/finishedCampsSub/%y/%m/%d')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishedCampImages', to='campApp.activecamps')),
            ],
        ),
    ]
