# Generated by Django 4.1.7 on 2023-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0009_finishedcampvideos_finishedcamps_finishedcampimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecamps',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
