# Generated by Django 4.1.7 on 2023-03-19 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0010_activecamps_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedcamps',
            name='av_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
