# Generated by Django 4.1.7 on 2023-03-19 21:16

import campApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0011_finishedcamps_av_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedcamps',
            name='av_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='finishedcamps',
            name='started_date',
            field=models.DateField(help_text='Enter the Start date of Camp It Must Be greater Less Today', validators=[campApp.models.no_future]),
        ),
    ]
