# Generated by Django 4.1.7 on 2023-03-23 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campApp', '0015_alter_campsenrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsenrollment',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campsenrollment',
            name='state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campsenrollment',
            name='zip_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AttendeesNamesAges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(12)])),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendeesNamesAges', to='campApp.campsenrollment')),
            ],
        ),
    ]
