# Generated by Django 4.1.6 on 2023-04-01 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsenrollment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='campsenrollment',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='campsenrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campsenrollment',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsenrollment',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='camp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qrCode', to='campApp.campsenrollment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendeesnamesages',
            name='age',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='campsenrollment',
            name='city',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AlterField(
            model_name='campsenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsEnrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
