# Generated by Django 4.1.6 on 2023-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=0, upload_to='media/user/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
