# Generated by Django 4.1.6 on 2023-03-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
    ]
